### ISSUE TITLE
remove prefix

### ISSUE THREAD

**Issue by Vuscin** [LinsMinecraftStudio/FakePlayerMakerRecoded#3]
Hello, is there a way to remove the tag before the name? I understand it's use, but in my application it is not going to work.
![image](https://github.com/LinsMinecraftStudio/FakePlayerMakerRecoded/assets/165175858/b6001136-3461-4fd3-a320-3412735736c0)

**Comment by lijinhong11** [comment]
1.Open config.yml
2.leave the prefix blank
